@BASE=http://127.0.0.1:80

###
GET {{BASE}}/healthz
Content-Type: application/json


###
POST {{BASE}}/api/ssl/v1/ca/init?token=MQ8wDQYDVQQHEwZEYWxpYW4x&key=tst
Content-Type: application/json

{
  "CN": "Kubernetes",
  "key": {
    "size": 2048
  },
  "CA":{
    "expiry":"20y",
    "name": {
      "O": "Kubernetes",
      "OU": "CA"
    }
  },
  "profiles": {
    "default": {
      "expiry": "10y",
      "name": {
        "O": "Kubernetes",
        "OU": "CA"
      }
    },
    "profile": {
      "expiry": "30d",
      "name": {
        "O": "profile",
        "OU": "CA"
      }
    }
  }
}

###
POST {{BASE}}/api/ssl/v1/ca/init?token=v4d050b629c0c4ed72d8c475d681115&key=tst
Content-Type: application/json


{
  "profiles": {
    "default": {
      "expiry": "10y",
      "name": {
        "O": "default",
        "OU": "CA"
      }
    },
    "profile": {
      "expiry": "30d",
      "name": {
        "O": "profile",
        "OU": "CA"
      }
    }
  }
}

###
GET {{BASE}}/api/ssl/v1/ca?key=tst

###
GET {{BASE}}/api/ssl/v1/ca/txt?key=tst

###
GET {{BASE}}/api/ssl/v1/ca/b64?key=tst


###
GET {{BASE}}/api/ssl/v1/ce?token=Ckt1YmVybmV0ZXM&key=tst&domain=dev1.sims-cn.com&profile=&kind=1&cn=dev01
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=v4d050b629c0c4ed72d8c475d6811150&key=tst&domain=dev1.sims-cn.com&profile=&kind=3&cn=dev01
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=v4d050b629c0c4ed72d8c475d6811150&key=tst&domain=dev2.sims-cn.com&profile=&kind=1&cn=dev02
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=v4d050b629c0c4ed72d8c475d6811150&key=tst&domain=dev3.sims-cn.com&profile=&kind=1&cn=dev03
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=v4d050b629c0c4ed72d8c475d6811150&key=tst&domain=dev4.sims-cn.com&profile=&kind=1&cn=dev04
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=v4d050b629c0c4ed72d8c475d6811150&key=tst&domain=dev5.sims-cn.com&profile=&kind=1&cn=dev05
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=v4d050b629c0c4ed72d8c475d6811150&key=tst&domain=dev6.sims-cn.com
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=&key=tst&domain=dev5.sims-cn.com&kind=1
Content-Type: application/json
