@BASE=http://127.0.0.1:80

### 
GET {{BASE}}/healthz
Content-Type: application/json
X-Request-Rt: 2

### 
GET {{BASE}}/?action=hello
Content-Type: application/json

### 
GET {{BASE}}/img/1/1ss
Content-Type: application/json

### 
GET {{BASE}}/zgg/img/1/1ss
Content-Type: application/json

### 
GET {{BASE}}/demo1/demo2/img/1/1ss
Content-Type: application/json


### 
GET {{BASE}}/zgg//file/%2Fdocs%2Freadme.txt
Content-Type: application/json

### 
GET {{BASE}}/demo2/demo2/img/demo.jpeg?action=hello
Content-Type: application/json

### 
GET {{BASE}}/zgg/img/demo.jpeg?action=hello
Content-Type: application/json

### 
GET {{BASE}}/?action=xxx
Content-Type: application/json

### 
@BASE=http://frontend.default.svc
### 
GET {{BASE}}/front3/webhook?method=update.image&akey=66666666&image=dcr.dev.sims-cn.com/plus/iam-signin:v1.0.153&app=sso
Content-Type: application/json

### 
# @BASE=http://127.0.0.1:8088
### 
GET {{BASE}}/?action=xxx
Content-Type: application/json
Host: sso.kfzx.sims-cn.com
