@BASE=http://127.0.0.1:81

### curl --cacert _out/_sa.crt https://127.0.0.1/healthz
### curl --cacert _out/_sa.crt https://localhost/healthz
GET {{BASE}}/healthz
Content-Type: application/json


###
POST {{BASE}}/api/ssl/v1/ca/init?token=v3045f3e1c4c43062a1bb393cb90f4ed&key=dev&cn=kubernetes
Content-Type: application/json

{
  "kubernetes": {
    "expiry": "20y",
    "name": {
      "O": "Kubernetes",
      "OU": "CA"
    }
  },
  "default": {
    "expiry": "10y",
    "name": {
      "O": "Kubernetes",
      "OU": "CA"
    }
  },
  "profile": {
    "expiry": "30d",
    "name": {
      "O": "profile",
      "OU": "CA"
    }
  }
}

###
POST {{BASE}}/api/ssl/v1/ca/init?token=v3045f3e1c4c43062a1bb393cb90f4ed&key=tst
Content-Type: application/json


{
  "default": {
    "expiry": "5y",
    "name": {
      "O": "default",
      "OU": "CA"
    }
  },
  "profile": {
    "expiry": "60d",
    "name": {
      "O": "profile",
      "OU": "CA"
    }
  }
}

###
GET {{BASE}}/api/ssl/v1/ca?key=tst

###
GET {{BASE}}/api/ssl/v1/ca/txt?key=tst

###
GET {{BASE}}/api/ssl/v1/ca/b64?key=tst

###
GET {{BASE}}/api/ssl/v1/ca/txt?key=ksidecar

###
GET {{BASE}}/api/ssl/v1/ca/b64?key=ksidecar

###
GET {{BASE}}/api/ssl/v1/ce?token=v3df7817b25a410fea1be77c50cd172b&key=tst&domain=dev1.sims-cn.com&kind=1&cn=dev01
Content-Type: application/json

### kind=1: 没有新建， kind=3: 强制新建， cn: common name, profile使用的key， 如不没有，使用 default
GET {{BASE}}/api/ssl/v1/ce?token=v3df7817b25a410fea1be77c50cd172b&key=tst&domain=dev1.sims-cn.com&kind=3&cn=dev01
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=v34ed884903b854540a8c86299fe2308&key=tst&domain=dev2.sims-cn.com&kind=1&cn=dev02
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=v34ed884903b854540a8c86299fe2308&key=tst&domain=dev3.sims-cn.com&kind=1&cn=dev03
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=v34ed884903b854540a8c86299fe2308&key=tst&domain=dev4.sims-cn.com&kind=1&cn=dev04
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=v34ed884903b854540a8c86299fe2308&key=tst&domain=dev5.sims-cn.com&domain=dev7.sims-cn.com&kind=1&cn=dev05
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=v34ed884903b854540a8c86299fe2308&key=tst&domain=dev6.sims-cn.com
Content-Type: application/json

###
GET {{BASE}}/api/ssl/v1/ce?token=&key=tst&domain=dev5.sims-cn.com&kind=1
Content-Type: application/json
